#! /bin/zsh
rm -rf .dvc .git

git init
dvc init

export INPUT=42
export IMAGE=pipeline1
export MODULE_FUNCTION=pipeline1.my_pipeline
merkl dot --cache dvc $MODULE_FUNCTION $INPUT | dot -Tpng -o$IMAGE.png
export OUTPUT="$(merkl run --cache dvc $MODULE_FUNCTION $INPUT)"
export FILENAME=pipeline1.py
export CODE="$(cat $FILENAME)"
export TABLE1="$(envsubst < table_template.md)"

merkl dot --cache dvc pipeline1.my_pipeline 42 | dot -Tpng -opipeline1_2.png
merkl dot --cache dvc pipeline1_2.my_pipeline 42 | dot -Tpng -opipeline1_3.png

dvc add train.csv test.csv


export INPUT=""
export IMAGE=pipeline2
export MODULE_FUNCTION=pipeline2.train_eval
merkl dot --cache dvc $MODULE_FUNCTION $INPUT | dot -Tpng -o$IMAGE.png
export OUTPUT="$(merkl run --cache dvc $MODULE_FUNCTION $INPUT)"
export FILENAME=pipeline2.py
export CODE="$(cat $FILENAME)"
export TABLE2="$(envsubst < table_template.md)"

rm -rf .dvc .git .gitignore .dvcignore train.csv* test.csv* model.csv*

envsubst < README_template.md > ../README.md
